### ISSUE TITLE
version 1.2.10 breaks on older chef versions

### ISSUE THREAD

**Issue by zts** [opscode-cookbooks/xml#21]
version 1.2.9 works fine on chef 11.whatever, while 1.2.10 fails as chef_gem's "compile_time" parameter doesn't exist.

I would suggest that this should have received a larger version bump, and clear warnings that this cookbook is no longer supported on chef clients < 12.1.x (I believe that's where the compile_time parameter was added?).

Minor other note: changelog dates 1.2.10 as 2014-02-17, when it should be 2015-02-17.

**Comment by liquid-sky** [comment]
Can confirm this issue with chef client 11.16.4.

**Comment by someara** [comment]
Sorry about that. Fixed in the latest patch release

**Comment by liquid-sky** [comment]
The fix isn't working with chef 11.16.4: 

```
  ArgumentError
  -------------
  wrong number of arguments (1 for 0)

  Cookbook Trace:
  ---------------
    ../xml/recipes/ruby.rb:44:in `block in from_file'
    ../xml/recipes/ruby.rb:43:in `from_file'
    ../route53/recipes/default.rb:20:in `from_file'
    ../route53/recipes/route53.rb:2:in `from_file'

   43:  chef_gem 'nokogiri' do
   44>>   compile_time true if respond_to?(:compile_time)
   45:    version node['xml']['nokogiri']['version']
   46:    action :install
   47:  end
```

**Comment by scalp42** [comment]
Same issue here @someara @liquid-sky

**Comment by arnaud036** [comment]
+1 @someara
